[package]
name = "workshop-protocol"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
workspace-hack.workspace = true

[build-dependencies]
build-ceiling.workspace = true

[lints]
workspace = true
