[package]
name = "build-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
build-ceiling.workspace = true

[lints]
workspace = true
