// Guard for the workspace-debt removal (plan step 7): the repository's
// prose describes the shipped behavior. Each phrase below was once true
// and is now stale, so its return would mean a doc was reverted or a
// paragraph copied from history. Reads the files with node:fs rather
// than importing anything, so the check needs no bundle and runs in the
// plain SPA suite.
// Run: node --test test/docs-claims.mjs
import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..", "..");

/** Every line of `file` (relative to the repo root) matching `phrase`, tagged with its number. */
async function offendingLines(file, phrase) {
  const text = await readFile(path.join(repoRoot, file), "utf8");
  return text
    .split("\n")
    .map((line, index) => ({ line, number: index + 1 }))
    .filter(({ line }) => line.includes(phrase))
    .map(({ line, number }) => `${file}:${number}: ${line.trim()}`);
}

/** Every `.md` file under `dir` (relative to the repo root), sorted, as repo-relative paths. */
async function markdownFiles(dir) {
  const entries = await readdir(path.join(repoRoot, dir), { recursive: true, withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => path.relative(repoRoot, path.join(entry.parentPath ?? entry.path, entry.name)))
    .sort();
}

test("AGENTS.md names two UI-state homes, not a TOML config or three buckets", async () => {
  // UM-002: the SPA rule once routed "account preferences" to a
  // "machine-written TOML config" that no code, route, or allow-list
  // implements, and counted three buckets where two exist.
  for (const phrase of ["TOML config", "three named buckets", "three homes"]) {
    assert.deepEqual(await offendingLines("AGENTS.md", phrase), [], `AGENTS.md still says "${phrase}"`);
  }
});

// OP-002: zoom persists through /user/state, so "storage is blocked,
// such as in private mode" no longer describes a real failure.
// TWF-003: an Open Recent workspace row now opens the workspace, so
// the list is no longer "a record only".
// One list guards both the sources and the export so a regeneration
// that landed between the two source fixes cannot slip one phrase through.
const STALE_GUIDE_PHRASES = ["storage is blocked", "a record only"];

test("the guide sources carry no stale zoom or Open Recent claims", async () => {
  const files = await markdownFiles(path.join("guide", "src"));
  assert.ok(files.length > 0, "guide/src holds no markdown; the walk is broken");
  for (const phrase of STALE_GUIDE_PHRASES) {
    const offenders = [];
    for (const file of files) offenders.push(...(await offendingLines(file, phrase)));
    assert.deepEqual(offenders, [], `guide/src still says "${phrase}"`);
  }
});

test("the tracked guide export matches the sources on the stale claims", async () => {
  // The single-file export is regenerated by `cargo run -p build-user-guide`;
  // a source fix that skipped the regeneration leaves the export stale.
  const exportFile = path.join("guide", "promptforge-workshop-guide.md");
  for (const phrase of STALE_GUIDE_PHRASES) {
    assert.deepEqual(
      await offendingLines(exportFile, phrase),
      [],
      `guide/promptforge-workshop-guide.md still says "${phrase}"; rerun build-user-guide`,
    );
  }
});
