//! Revision-pinned Hugging Face model identifiers for template families.

use super::Family;

pub(super) const MODEL_FAMILIES: &[(&str, Family)] = &[
    ("allenai/llama-3.1-tulu-3-70b", Family::Llama31),
    ("allenai/llama-3.1-tulu-3-8b", Family::Llama31),
    ("google/gemma-3-12b-it", Family::Gemma3),
    ("google/gemma-3-1b-it", Family::Gemma3),
    ("google/gemma-3-27b-it", Family::Gemma3),
    ("google/gemma-3-4b-it", Family::Gemma3),
    ("google/gemma-4-26b-a4b-it", Family::Gemma4),
    ("google/gemma-4-31b-it", Family::Gemma4),
    ("google/gemma-4-e2b-it", Family::Gemma4),
    ("google/gemma-4-e4b-it", Family::Gemma4),
    ("google/medgemma-27b-text-it", Family::Gemma3),
    ("google/medgemma-4b-it", Family::Gemma3),
    ("huggingfaceh4/mistral-7b-sft-beta", Family::Zephyr),
    ("meta-llama/llama-3.1-8b-instruct", Family::Llama31),
    ("meta-llama/llama-3.2-1b-instruct", Family::Llama31),
    ("meta-llama/llama-3.2-3b-instruct", Family::Llama31),
    ("meta-llama/llama-3.3-70b-instruct", Family::Llama31),
    ("meta-llama/meta-llama-3-70b-instruct", Family::Llama3),
    ("meta-llama/meta-llama-3-8b-instruct", Family::Llama3),
    ("meta-llama/meta-llama-3.1-405b-instruct", Family::Llama31),
    ("meta-llama/meta-llama-3.1-70b-instruct", Family::Llama31),
    ("meta-llama/meta-llama-3.1-8b-instruct", Family::Llama31),
    ("microsoft/phi-3-medium-4k-instruct", Family::Phi3),
    ("microsoft/phi-3-mini-4k-instruct", Family::Phi3),
    ("microsoft/phi-3.5-mini-instruct", Family::Phi3),
    ("microsoft/phi-4", Family::Phi4),
    ("mistralai/mistral-7b-instruct-v0.1", Family::Mistral),
    ("mistralai/mistral-7b-instruct-v0.2", Family::Mistral),
    ("nousresearch/hermes-2-pro-mistral-7b", Family::Chatml),
    ("nousresearch/hermes-3-llama-3.1-405b", Family::Llama31),
    ("nousresearch/hermes-3-llama-3.1-70b", Family::Llama31),
    ("nousresearch/hermes-3-llama-3.1-8b", Family::Llama31),
    ("openai/gpt-oss-120b", Family::GptOss),
    ("openai/gpt-oss-20b", Family::GptOss),
    ("qwen/qwen2.5-0.5b-instruct", Family::Qwen25),
    ("qwen/qwen2.5-1.5b-instruct", Family::Qwen25),
    ("qwen/qwen2.5-14b-instruct", Family::Qwen25),
    ("qwen/qwen2.5-32b-instruct", Family::Qwen25),
    ("qwen/qwen2.5-3b-instruct", Family::Qwen25),
    ("qwen/qwen2.5-72b-instruct", Family::Qwen25),
    ("qwen/qwen2.5-7b-instruct", Family::Qwen25),
    ("qwen/qwen2.5-math-1.5b-instruct", Family::Qwen25),
    ("qwen/qwen2.5-math-72b-instruct", Family::Qwen25),
    ("qwen/qwen2.5-math-7b-instruct", Family::Qwen25),
    ("qwen/qwen3-0.6b", Family::Qwen3),
    ("qwen/qwen3-1.7b", Family::Qwen3),
    ("qwen/qwen3-14b", Family::Qwen3),
    ("qwen/qwen3-30b-a3b", Family::Qwen3),
    ("qwen/qwen3-32b", Family::Qwen3),
    ("qwen/qwen3-4b", Family::Qwen3),
    ("qwen/qwen3-8b", Family::Qwen3),
    ("teknium/openhermes-2.5-mistral-7b", Family::Chatml),
    ("unsloth/gemma-3-12b-it", Family::Gemma3),
    ("unsloth/gemma-3-12b-it-bnb-4bit", Family::Gemma3),
    ("unsloth/gemma-3-12b-it-unsloth-bnb-4bit", Family::Gemma3),
    ("unsloth/gemma-3-1b-it", Family::Gemma3),
    ("unsloth/gemma-3-1b-it-bnb-4bit", Family::Gemma3),
    ("unsloth/gemma-3-1b-it-unsloth-bnb-4bit", Family::Gemma3),
    ("unsloth/gemma-3-27b-it", Family::Gemma3),
    ("unsloth/gemma-3-27b-it-bnb-4bit", Family::Gemma3),
    ("unsloth/gemma-3-27b-it-unsloth-bnb-4bit", Family::Gemma3),
    ("unsloth/gemma-3-4b-it", Family::Gemma3),
    ("unsloth/gemma-3-4b-it-bnb-4bit", Family::Gemma3),
    ("unsloth/gemma-3-4b-it-unsloth-bnb-4bit", Family::Gemma3),
    ("unsloth/gemma-4-26b-a4b", Family::Gemma4),
    ("unsloth/gemma-4-26b-a4b-it", Family::Gemma4),
    ("unsloth/gemma-4-31b", Family::Gemma4),
    ("unsloth/gemma-4-31b-it", Family::Gemma4),
    ("unsloth/gemma-4-31b-it-unsloth-bnb-4bit", Family::Gemma4),
    ("unsloth/gemma-4-e2b", Family::Gemma4),
    ("unsloth/gemma-4-e2b-it", Family::Gemma4),
    ("unsloth/gemma-4-e2b-it-unsloth-bnb-4bit", Family::Gemma4),
    ("unsloth/gemma-4-e4b", Family::Gemma4),
    ("unsloth/gemma-4-e4b-it", Family::Gemma4),
    ("unsloth/gemma-4-e4b-it-unsloth-bnb-4bit", Family::Gemma4),
    ("unsloth/gpt-oss-120b", Family::GptOss),
    ("unsloth/gpt-oss-120b-unsloth-bnb-4bit", Family::GptOss),
    ("unsloth/gpt-oss-20b", Family::GptOss),
    ("unsloth/gpt-oss-20b-unsloth-bnb-4bit", Family::GptOss),
    ("unsloth/hermes-2-pro-mistral-7b", Family::Chatml),
    ("unsloth/hermes-2-pro-mistral-7b-bnb-4bit", Family::Chatml),
    ("unsloth/hermes-3-llama-3.1-405b-bnb-4bit", Family::Llama31),
    ("unsloth/hermes-3-llama-3.1-70b", Family::Llama31),
    ("unsloth/hermes-3-llama-3.1-70b-bnb-4bit", Family::Llama31),
    ("unsloth/hermes-3-llama-3.1-8b", Family::Llama31),
    ("unsloth/hermes-3-llama-3.1-8b-bnb-4bit", Family::Llama31),
    ("unsloth/llama-3-70b-instruct-bnb-4bit", Family::Llama3),
    ("unsloth/llama-3-8b-instruct", Family::Llama3),
    ("unsloth/llama-3-8b-instruct-bnb-4bit", Family::Llama3),
    ("unsloth/llama-3.1-8b-instruct", Family::Llama31),
    ("unsloth/llama-3.1-8b-instruct-bnb-4bit", Family::Llama31),
    (
        "unsloth/llama-3.1-8b-instruct-unsloth-bnb-4bit",
        Family::Llama31,
    ),
    ("unsloth/llama-3.1-tulu-3-70b", Family::Llama31),
    ("unsloth/llama-3.1-tulu-3-70b-bnb-4bit", Family::Llama31),
    ("unsloth/llama-3.1-tulu-3-8b", Family::Llama31),
    ("unsloth/llama-3.1-tulu-3-8b-bnb-4bit", Family::Llama31),
    ("unsloth/llama-3.2-1b-instruct", Family::Llama31),
    ("unsloth/llama-3.2-1b-instruct-bnb-4bit", Family::Llama31),
    (
        "unsloth/llama-3.2-1b-instruct-unsloth-bnb-4bit",
        Family::Llama31,
    ),
    ("unsloth/llama-3.2-3b-instruct", Family::Llama31),
    ("unsloth/llama-3.2-3b-instruct-bnb-4bit", Family::Llama31),
    (
        "unsloth/llama-3.2-3b-instruct-unsloth-bnb-4bit",
        Family::Llama31,
    ),
    ("unsloth/llama-3.3-70b-instruct", Family::Llama31),
    ("unsloth/llama-3.3-70b-instruct-bnb-4bit", Family::Llama31),
    ("unsloth/medgemma-27b-text-it", Family::Gemma3),
    ("unsloth/medgemma-27b-text-it-bnb-4bit", Family::Gemma3),
    (
        "unsloth/medgemma-27b-text-it-unsloth-bnb-4bit",
        Family::Gemma3,
    ),
    ("unsloth/medgemma-4b-it", Family::Gemma3),
    ("unsloth/medgemma-4b-it-bnb-4bit", Family::Gemma3),
    ("unsloth/medgemma-4b-it-unsloth-bnb-4bit", Family::Gemma3),
    (
        "unsloth/meta-llama-3.1-405b-instruct-bnb-4bit",
        Family::Llama31,
    ),
    ("unsloth/meta-llama-3.1-70b-instruct", Family::Llama31),
    (
        "unsloth/meta-llama-3.1-70b-instruct-bnb-4bit",
        Family::Llama31,
    ),
    ("unsloth/meta-llama-3.1-8b-instruct", Family::Llama31),
    (
        "unsloth/meta-llama-3.1-8b-instruct-bnb-4bit",
        Family::Llama31,
    ),
    (
        "unsloth/meta-llama-3.1-8b-instruct-unsloth-bnb-4bit",
        Family::Llama31,
    ),
    ("unsloth/mistral-7b-instruct-v0.1", Family::Mistral),
    ("unsloth/mistral-7b-instruct-v0.1-bnb-4bit", Family::Mistral),
    ("unsloth/mistral-7b-instruct-v0.2", Family::Mistral),
    ("unsloth/mistral-7b-instruct-v0.2-bnb-4bit", Family::Mistral),
    ("unsloth/openhermes-2.5-mistral-7b", Family::Chatml),
    ("unsloth/openhermes-2.5-mistral-7b-bnb-4bit", Family::Chatml),
    ("unsloth/phi-3-medium-4k-instruct", Family::Phi3),
    ("unsloth/phi-3-medium-4k-instruct-bnb-4bit", Family::Phi3),
    ("unsloth/phi-3-mini-4k-instruct", Family::Phi3),
    ("unsloth/phi-3-mini-4k-instruct-bnb-4bit", Family::Phi3),
    ("unsloth/phi-3-mini-4k-instruct-v0", Family::Phi3),
    ("unsloth/phi-3-mini-4k-instruct-v0-bnb-4bit", Family::Phi3),
    ("unsloth/phi-3.5-mini-instruct", Family::Phi3),
    ("unsloth/phi-3.5-mini-instruct-bnb-4bit", Family::Phi3),
    ("unsloth/phi-4", Family::Phi4),
    ("unsloth/phi-4-bnb-4bit", Family::Phi4),
    ("unsloth/phi-4-unsloth-bnb-4bit", Family::Phi4),
    ("unsloth/qwen2.5-0.5b-instruct", Family::Qwen25),
    ("unsloth/qwen2.5-0.5b-instruct-bnb-4bit", Family::Qwen25),
    (
        "unsloth/qwen2.5-0.5b-instruct-unsloth-bnb-4bit",
        Family::Qwen25,
    ),
    ("unsloth/qwen2.5-1.5b-instruct", Family::Qwen25),
    ("unsloth/qwen2.5-1.5b-instruct-bnb-4bit", Family::Qwen25),
    (
        "unsloth/qwen2.5-1.5b-instruct-unsloth-bnb-4bit",
        Family::Qwen25,
    ),
    ("unsloth/qwen2.5-14b-instruct", Family::Qwen25),
    ("unsloth/qwen2.5-14b-instruct-bnb-4bit", Family::Qwen25),
    (
        "unsloth/qwen2.5-14b-instruct-unsloth-bnb-4bit",
        Family::Qwen25,
    ),
    ("unsloth/qwen2.5-32b-instruct", Family::Qwen25),
    ("unsloth/qwen2.5-32b-instruct-bnb-4bit", Family::Qwen25),
    ("unsloth/qwen2.5-3b-instruct", Family::Qwen25),
    ("unsloth/qwen2.5-3b-instruct-bnb-4bit", Family::Qwen25),
    (
        "unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit",
        Family::Qwen25,
    ),
    ("unsloth/qwen2.5-72b-instruct", Family::Qwen25),
    ("unsloth/qwen2.5-72b-instruct-bnb-4bit", Family::Qwen25),
    ("unsloth/qwen2.5-7b-instruct", Family::Qwen25),
    ("unsloth/qwen2.5-7b-instruct-bnb-4bit", Family::Qwen25),
    (
        "unsloth/qwen2.5-7b-instruct-unsloth-bnb-4bit",
        Family::Qwen25,
    ),
    ("unsloth/qwen2.5-math-1.5b-instruct", Family::Qwen25),
    (
        "unsloth/qwen2.5-math-1.5b-instruct-bnb-4bit",
        Family::Qwen25,
    ),
    ("unsloth/qwen2.5-math-72b-instruct", Family::Qwen25),
    ("unsloth/qwen2.5-math-72b-instruct-bnb-4bit", Family::Qwen25),
    ("unsloth/qwen2.5-math-7b-instruct", Family::Qwen25),
    ("unsloth/qwen2.5-math-7b-instruct-bnb-4bit", Family::Qwen25),
    ("unsloth/qwen3-0.6b", Family::Qwen3),
    ("unsloth/qwen3-0.6b-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-0.6b-unsloth-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-1.7b", Family::Qwen3),
    ("unsloth/qwen3-1.7b-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-1.7b-unsloth-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-14b", Family::Qwen3),
    ("unsloth/qwen3-14b-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-14b-unsloth-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-30b-a3b", Family::Qwen3),
    ("unsloth/qwen3-30b-a3b-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-30b-a3b-unsloth-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-32b", Family::Qwen3),
    ("unsloth/qwen3-32b-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-32b-unsloth-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-4b", Family::Qwen3),
    ("unsloth/qwen3-4b-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-4b-unsloth-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-8b", Family::Qwen3),
    ("unsloth/qwen3-8b-bnb-4bit", Family::Qwen3),
    ("unsloth/qwen3-8b-unsloth-bnb-4bit", Family::Qwen3),
    ("unsloth/zephyr-sft", Family::Zephyr),
    ("unsloth/zephyr-sft-bnb-4bit", Family::Zephyr),
];
