[package]
name = "shared-loopback"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
axum.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
tokio.workspace = true
tower.workspace = true

[build-dependencies]
build-ceiling.workspace = true

[lints]
workspace = true
