//! End-to-end CUDA bundle build: verify, compile, account, embed.

use std::path::{Path, PathBuf};

use anyhow::Context as _;

use crate::manifest::{
    BUNDLE_FORMAT_VERSION, BundleFile, LINKAGE_POLICY, Manifest, SourceIdentity, ToolIdentity,
    sha256_hex,
};
use crate::probe::{CommandRequest, Probe, SystemProbe};
use crate::target::TargetInfo;
use crate::{arch, cmake, deps, submodule, toolchain};

/// What the build produced; the build script forwards the rerun triggers.
#[derive(Debug)]
pub struct BuildReport {
    /// Files Cargo should watch for changes.
    pub rerun_if_changed: Vec<PathBuf>,
    /// True when the CUDA bundle was built (native Windows x86-64 only).
    pub built: bool,
}

/// Runs the full bundle build against the real environment and toolchain.
///
/// No-ops on targets other than Windows x86-64. Writes only under
/// `OUT_DIR`.
///
/// # Errors
/// Returns an error when the target is a cross-compile, the submodule is
/// absent or drifted, the CUDA Toolkit is missing or too old, any build
/// command fails, the dependency closure is incomplete, or the smoke check
/// finds no CUDA device.
pub fn build() -> anyhow::Result<BuildReport> {
    let env = |name: &str| std::env::var(name).ok();
    let manifest_dir = env("CARGO_MANIFEST_DIR").context("CARGO_MANIFEST_DIR is unset")?;
    let out_dir = env("OUT_DIR").context("OUT_DIR is unset")?;
    let workspace = Path::new(&manifest_dir)
        .ancestors()
        .nth(2)
        .context("CARGO_MANIFEST_DIR has no workspace root ancestor")?
        .to_path_buf();
    build_with(&SystemProbe, &env, &workspace, Path::new(&out_dir))
}

/// Runs `request` and requires exit code zero, bounding the failure output.
fn run_checked(probe: &impl Probe, request: &CommandRequest, phase: &str) -> anyhow::Result<()> {
    let output = probe
        .run(request)
        .with_context(|| format!("{phase} invocation"))?;
    anyhow::ensure!(
        output.success(),
        "{phase} failed (exit {}) running `{}`:\n{}",
        output.code,
        request.display_line(),
        output.stderr
    );
    Ok(())
}

/// Collects the runtime files the build emitted: `llama-server.exe` plus
/// every DLL beside it, sorted by name with hashes.
fn collect_runtime_files(stage: &Path) -> anyhow::Result<Vec<BundleFile>> {
    anyhow::ensure!(
        stage.is_dir(),
        "llama-server build produced no runtime directory at {}",
        stage.display()
    );
    let mut names = Vec::new();
    for entry in std::fs::read_dir(stage).with_context(|| format!("read {}", stage.display()))? {
        let name = entry?.file_name().to_string_lossy().into_owned();
        if name == "llama-server.exe" || name.to_ascii_lowercase().ends_with(".dll") {
            names.push(name);
        }
    }
    anyhow::ensure!(
        names.iter().any(|name| name == "llama-server.exe"),
        "llama-server.exe is missing from {}",
        stage.display()
    );
    names.sort();
    let mut files = Vec::new();
    for name in names {
        let bytes = std::fs::read(stage.join(&name)).with_context(|| format!("read {name}"))?;
        files.push(BundleFile {
            size: bytes.len() as u64,
            sha256: sha256_hex(&bytes),
            name,
        });
    }
    Ok(files)
}

/// Locates `dumpbin.exe` through `vswhere`, returning the tool and the
/// directory the child needs on `PATH` for its own DLLs.
fn locate_dumpbin(
    probe: &impl Probe,
    env: &impl Fn(&str) -> Option<String>,
) -> anyhow::Result<(PathBuf, PathBuf)> {
    let vswhere = toolchain::vswhere_path(env)
        .context("vswhere.exe not found; a Visual Studio C++ workload is required")?;
    let request = CommandRequest::new(&vswhere).args([
        "-latest",
        "-products",
        "*",
        "-requires",
        "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
        "-find",
        "VC\\Tools\\MSVC\\*\\bin\\Hostx64\\x64\\dumpbin.exe",
    ]);
    let output = probe.run(&request).context("locate dumpbin")?;
    anyhow::ensure!(
        output.success(),
        "vswhere failed (exit {}):\n{}",
        output.code,
        output.stderr
    );
    let dumpbin = output
        .stdout
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty())
        .context("vswhere found no dumpbin.exe")?;
    let dumpbin = PathBuf::from(dumpbin);
    let dir = dumpbin
        .parent()
        .context("dumpbin path has no parent")?
        .to_path_buf();
    Ok((dumpbin, dir))
}

/// Renders the generated Rust module embedding the manifest and files.
fn render_codegen(manifest_path: &Path, bundle_dir: &Path, files: &[BundleFile]) -> String {
    use std::fmt::Write as _;

    fn forward(path: &Path) -> String {
        path.display().to_string().replace('\\', "/")
    }
    let mut code = String::from("// @generated by promptforge-gateway build.rs; do not edit.\n");
    let _ = writeln!(
        code,
        "pub(crate) const MANIFEST: &str = include_str!(\"{}\");",
        forward(manifest_path)
    );
    code.push_str("pub(crate) static FILES: &[(&str, &[u8])] = &[\n");
    for file in files {
        let _ = writeln!(
            code,
            "    (\"{}\", include_bytes!(\"{}\")),",
            file.name,
            forward(&bundle_dir.join(&file.name))
        );
    }
    code.push_str("];\n");
    code
}

/// Resolved toolchain facts for one build.
struct Toolchain {
    nvcc_path: PathBuf,
    nvcc_version: String,
    toolkit_version: String,
    cmake_path: PathBuf,
    cmake_version: String,
}

/// Resolves nvcc and CMake, probes their versions, and enforces the
/// toolkit floor.
fn probe_toolchain(
    probe: &impl Probe,
    env: &impl Fn(&str) -> Option<String>,
) -> anyhow::Result<Toolchain> {
    let nvcc_path = toolchain::resolve_tool("nvcc", env)
        .context("CUDA Toolkit not found: `nvcc` is not on PATH; install CUDA >= 12.8")?;
    let nvcc_out = probe
        .run(&CommandRequest::new(&nvcc_path).args(["--version"]))
        .context("probe nvcc")?;
    anyhow::ensure!(
        nvcc_out.success(),
        "nvcc --version failed:\n{}",
        nvcc_out.stderr
    );
    let (toolkit_version, nvcc_version) = toolchain::parse_nvcc_version(&nvcc_out.stdout)
        .context("unrecognized `nvcc --version` output")?;
    toolchain::require_toolkit(&toolkit_version)?;

    let cmake_path =
        toolchain::resolve_tool("cmake", env).context("cmake is not on PATH; install CMake")?;
    let cmake_out = probe
        .run(&CommandRequest::new(&cmake_path).args(["--version"]))
        .context("probe cmake")?;
    anyhow::ensure!(
        cmake_out.success(),
        "cmake --version failed:\n{}",
        cmake_out.stderr
    );
    let cmake_version = toolchain::parse_cmake_version(&cmake_out.stdout)
        .context("unrecognized `cmake --version` output")?;

    Ok(Toolchain {
        nvcc_path,
        nvcc_version,
        toolkit_version,
        cmake_path,
        cmake_version,
    })
}

/// Enumerates the executable's PE import closure through dumpbin and
/// returns the external DLL names the runtime host must provide.
fn inspect_closure(
    probe: &impl Probe,
    env: &impl Fn(&str) -> Option<String>,
    stage: &Path,
    files: &[BundleFile],
) -> anyhow::Result<Vec<String>> {
    let (dumpbin, dumpbin_dir) = locate_dumpbin(probe, env)?;
    let exe = stage.join("llama-server.exe");
    let deps_out = probe
        .run(
            &CommandRequest::new(&dumpbin)
                .args(["/dependents", &exe.display().to_string()])
                .path_prefix(&dumpbin_dir),
        )
        .context("inspect PE imports")?;
    anyhow::ensure!(
        deps_out.success(),
        "dumpbin failed (exit {}):\n{}",
        deps_out.code,
        deps_out.stderr
    );
    let imports = deps::parse_dumpbin_dependents(&deps_out.stdout);
    let bundled: Vec<String> = files.iter().map(|file| file.name.clone()).collect();
    deps::external_closure(&imports, &bundled)
}

/// Runs the staged executable's device-list operation and requires at
/// least one CUDA device in its output.
fn smoke_check(probe: &impl Probe, stage: &Path) -> anyhow::Result<()> {
    let exe = stage.join("llama-server.exe");
    let smoke = probe
        .run(
            &CommandRequest::new(&exe)
                .args(["--list-devices"])
                .cwd(stage),
        )
        .context("smoke-check llama-server")?;
    anyhow::ensure!(
        smoke.success() && smoke.stdout.contains("CUDA"),
        "llama-server --list-devices reported no CUDA device (exit {}):\n{}\n{}",
        smoke.code,
        smoke.stdout,
        smoke.stderr
    );
    Ok(())
}

/// Full pipeline, with the command seam and environment injected for tests.
pub(crate) fn build_with(
    probe: &impl Probe,
    env: &impl Fn(&str) -> Option<String>,
    workspace: &Path,
    out_dir: &Path,
) -> anyhow::Result<BuildReport> {
    let target = TargetInfo::from_env(env)?;
    let submodule = workspace.join("third_party/llama.cpp");
    // Watching HEAD is best-effort: an unresolvable git directory is fatal
    // only on Windows x86-64, where `submodule::verify` reports it.
    let rerun_if_changed = submodule::head_file(&submodule)
        .into_iter()
        .collect::<Vec<_>>();
    if !target.is_windows_x86_64() {
        return Ok(BuildReport {
            rerun_if_changed,
            built: false,
        });
    }
    target.require_native()?;
    submodule::verify(&submodule)?;

    let tools = probe_toolchain(probe, env)?;
    let architectures = arch::detect(probe)?;

    let build_dir = out_dir.join("llama-build");
    let (configure, build_cmd) = cmake::plan(
        &submodule,
        &build_dir,
        &tools.cmake_path,
        &architectures,
        &tools.nvcc_path,
    );
    run_checked(probe, &configure, "cmake configure")?;
    let cache = std::fs::read_to_string(build_dir.join("CMakeCache.txt"))
        .context("read CMakeCache.txt after configure")?;
    let identity = cmake::parse_cache(&cache)?;
    run_checked(probe, &build_cmd, "cmake build")?;

    let stage = build_dir.join("bin").join("Release");
    let files = collect_runtime_files(&stage)?;
    let external_dlls = inspect_closure(probe, env, &stage, &files)?;
    smoke_check(probe, &stage)?;

    let manifest = Manifest {
        bundle_format_version: BUNDLE_FORMAT_VERSION,
        source: SourceIdentity {
            url: submodule::SOURCE_URL.to_string(),
            commit: submodule::PINNED_COMMIT.to_string(),
        },
        target_triple: target.target.clone(),
        host_triple: target.host.clone(),
        msvc: ToolIdentity {
            path: identity.cxx_compiler.display().to_string(),
            version: identity.cxx_version,
        },
        cmake: ToolIdentity {
            path: tools.cmake_path.display().to_string(),
            version: tools.cmake_version,
        },
        nvcc: ToolIdentity {
            path: tools.nvcc_path.display().to_string(),
            version: tools.nvcc_version,
        },
        toolkit_version: tools.toolkit_version,
        architectures: architectures.clone(),
        cmake_options: cmake::configure_options(&architectures, &tools.nvcc_path),
        linkage: LINKAGE_POLICY.to_string(),
        external_dlls,
        files: files.clone(),
    };
    let manifest_path = out_dir.join("llama-cuda-manifest.json");
    std::fs::write(&manifest_path, manifest.render()?)
        .with_context(|| format!("write {}", manifest_path.display()))?;

    let bundle_dir = out_dir.join("llama-cuda-bundle");
    std::fs::create_dir_all(&bundle_dir)
        .with_context(|| format!("create {}", bundle_dir.display()))?;
    for file in &files {
        std::fs::copy(stage.join(&file.name), bundle_dir.join(&file.name))
            .with_context(|| format!("stage {}", file.name))?;
    }
    let codegen = render_codegen(&manifest_path, &bundle_dir, &files);
    std::fs::write(out_dir.join("llama_cuda_bundle.rs"), codegen)
        .context("write generated bundle module")?;

    Ok(BuildReport {
        rerun_if_changed,
        built: true,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::probe::fake::{FakeProbe, fail, ok};

    const NVCC_OUTPUT: &str = "nvcc: NVIDIA (R) Cuda compiler driver\n\
                               Cuda compilation tools, release 13.3, V13.3.73\n";
    const CACHE: &str = "CMAKE_GENERATOR:INTERNAL=Visual Studio 17 2022\n\
                         CMAKE_CXX_COMPILER:FILEPATH=C:/VS/VC/Tools/MSVC/14.44/bin/Hostx64/x64/cl.exe\n\
                         CMAKE_CXX_COMPILER_VERSION:STRING=19.44.35219.0\n";
    const DUMPBIN_OUTPUT: &str = "Dump of file llama-server.exe\n\
                                  \n\
                                  \x20 Image has the following dependencies:\n\
                                  \n\
                                  \x20   cublas64_13.dll\n\
                                  \x20   KERNEL32.dll\n\
                                  \n\
                                  \x20 Summary\n";

    /// A synthetic Windows host: workspace with a pinned submodule, an
    /// `OUT_DIR` pre-seeded with the tree a real cmake build would emit,
    /// and a tool directory holding fake `nvcc.exe`/`cmake.exe`.
    struct SyntheticHost {
        _temp: tempfile::TempDir,
        workspace: PathBuf,
        out_dir: PathBuf,
        tools: PathBuf,
        dumpbin: PathBuf,
        program_files_x86: PathBuf,
    }

    impl SyntheticHost {
        fn new() -> Self {
            let temp = tempfile::TempDir::new().unwrap();
            let root = temp.path();
            let workspace = root.join("ws");
            let submodule = workspace.join("third_party/llama.cpp");
            std::fs::create_dir_all(submodule.join(".git")).unwrap();
            std::fs::write(
                submodule.join("CMakeLists.txt"),
                b"cmake_minimum_required(VERSION 3.14)\n",
            )
            .unwrap();
            std::fs::write(
                submodule.join(".git/HEAD"),
                format!("{}\n", submodule::PINNED_COMMIT),
            )
            .unwrap();

            let out_dir = root.join("out");
            let stage = out_dir.join("llama-build/bin/Release");
            std::fs::create_dir_all(&stage).unwrap();
            std::fs::write(stage.join("llama-server.exe"), b"synthetic-exe").unwrap();
            std::fs::write(stage.join("ggml-cuda.dll"), b"synthetic-dll").unwrap();
            std::fs::write(out_dir.join("llama-build/CMakeCache.txt"), CACHE).unwrap();

            let tools = root.join("tools");
            std::fs::create_dir_all(&tools).unwrap();
            std::fs::write(tools.join("nvcc.exe"), b"").unwrap();
            std::fs::write(tools.join("cmake.exe"), b"").unwrap();

            let dumpbin_dir = root.join("vs/VC/Tools/MSVC/14.44/bin/Hostx64/x64");
            std::fs::create_dir_all(&dumpbin_dir).unwrap();
            let dumpbin = dumpbin_dir.join("dumpbin.exe");
            std::fs::write(&dumpbin, b"").unwrap();
            let program_files_x86 = root.join("pf");
            std::fs::create_dir_all(program_files_x86.join("Microsoft Visual Studio/Installer"))
                .unwrap();
            std::fs::write(
                program_files_x86.join("Microsoft Visual Studio/Installer/vswhere.exe"),
                b"",
            )
            .unwrap();

            Self {
                _temp: temp,
                workspace,
                out_dir,
                tools,
                dumpbin,
                program_files_x86,
            }
        }

        fn env(&self) -> impl Fn(&str) -> Option<String> + '_ {
            move |name| match name {
                "CARGO_CFG_TARGET_ARCH" => Some("x86_64".to_string()),
                "CARGO_CFG_TARGET_OS" => Some("windows".to_string()),
                "TARGET" | "HOST" => Some("x86_64-pc-windows-msvc".to_string()),
                "PATH" => Some(self.tools.display().to_string()),
                "PATHEXT" => Some(".exe".to_string()),
                "ProgramFiles(x86)" => Some(self.program_files_x86.display().to_string()),
                _ => None,
            }
        }

        fn probe(&self) -> FakeProbe {
            FakeProbe::default()
                .on("nvcc.exe --version", ok(NVCC_OUTPUT))
                .on("cmake.exe --version", ok("cmake version 4.4.2\n"))
                .on("nvidia-smi", ok("12.0\n"))
                .on("--build", ok(""))
                .on("-S", ok(""))
                .on("vswhere", ok(&format!("{}\n", self.dumpbin.display())))
                .on("dumpbin", ok(DUMPBIN_OUTPUT))
                .on(
                    "llama-server.exe",
                    ok("ggml_cuda_init: found 1 CUDA devices\nDevice 0: NVIDIA RTX PRO 6000\n"),
                )
        }
    }

    #[test]
    fn non_windows_target_noops() {
        let host = SyntheticHost::new();
        let env = |name: &str| match name {
            "CARGO_CFG_TARGET_ARCH" => Some("x86_64".to_string()),
            "CARGO_CFG_TARGET_OS" => Some("linux".to_string()),
            "TARGET" | "HOST" => Some("x86_64-unknown-linux-gnu".to_string()),
            _ => None,
        };
        let report = build_with(&host.probe(), &env, &host.workspace, &host.out_dir).unwrap();
        assert!(!report.built);
        assert!(!host.out_dir.join("llama_cuda_bundle.rs").exists());
    }

    #[test]
    fn cross_compilation_is_rejected() {
        let host = SyntheticHost::new();
        let env = |name: &str| match name {
            "CARGO_CFG_TARGET_ARCH" => Some("x86_64".to_string()),
            "CARGO_CFG_TARGET_OS" => Some("windows".to_string()),
            "TARGET" => Some("x86_64-pc-windows-msvc".to_string()),
            "HOST" => Some("aarch64-pc-windows-msvc".to_string()),
            _ => None,
        };
        let err = build_with(&host.probe(), &env, &host.workspace, &host.out_dir).unwrap_err();
        assert!(format!("{err:#}").contains("cross-compilation is not supported"));
    }

    #[test]
    fn submodule_drift_fails_the_build() {
        let host = SyntheticHost::new();
        std::fs::write(
            host.workspace.join("third_party/llama.cpp/.git/HEAD"),
            "0000000000000000000000000000000000000000\n",
        )
        .unwrap();
        let err =
            build_with(&host.probe(), &host.env(), &host.workspace, &host.out_dir).unwrap_err();
        assert!(format!("{err:#}").contains("drift"));
    }

    #[test]
    fn missing_cuda_toolkit_fails_the_build() {
        let temp = tempfile::TempDir::new().unwrap();
        let host = SyntheticHost::new();
        let empty = temp.path().join("empty");
        std::fs::create_dir_all(&empty).unwrap();
        let env = |name: &str| match name {
            "PATH" => Some(empty.display().to_string()),
            _ => host.env()(name),
        };
        let err = build_with(&host.probe(), &env, &host.workspace, &host.out_dir).unwrap_err();
        assert!(format!("{err:#}").contains("CUDA Toolkit not found"));
    }

    #[test]
    fn cmake_failure_reports_bounded_stderr() {
        let host = SyntheticHost::new();
        let probe = FakeProbe::default()
            .on("nvcc.exe --version", ok(NVCC_OUTPUT))
            .on("cmake.exe --version", ok("cmake version 4.4.2\n"))
            .on("nvidia-smi", ok("12.0\n"))
            .on("-S", fail(1, &"ninja: error\n".repeat(10_000)));
        let err = build_with(&probe, &host.env(), &host.workspace, &host.out_dir).unwrap_err();
        let message = format!("{err:#}");
        assert!(message.contains("cmake configure failed (exit 1)"));
        assert!(message.len() < crate::probe::OUTPUT_LIMIT + 4096);
    }

    #[test]
    fn smoke_check_requires_a_cuda_device() {
        let host = SyntheticHost::new();
        let probe = FakeProbe::default()
            .on("nvcc.exe --version", ok(NVCC_OUTPUT))
            .on("cmake.exe --version", ok("cmake version 4.4.2\n"))
            .on("nvidia-smi", ok("12.0\n"))
            .on("--build", ok(""))
            .on("-S", ok(""))
            .on("vswhere", ok("C:/VS/dumpbin.exe\n"))
            .on("dumpbin", ok(DUMPBIN_OUTPUT))
            .on("llama-server.exe", ok("no devices found\n"));
        let err = build_with(&probe, &host.env(), &host.workspace, &host.out_dir).unwrap_err();
        assert!(format!("{err:#}").contains("no CUDA device"));
    }

    #[test]
    fn full_synthetic_build_produces_manifest_and_codegen() {
        let host = SyntheticHost::new();
        let probe = host.probe();
        let report = build_with(&probe, &host.env(), &host.workspace, &host.out_dir).unwrap();
        assert!(report.built);
        assert!(!report.rerun_if_changed.is_empty());

        let manifest_text =
            std::fs::read_to_string(host.out_dir.join("llama-cuda-manifest.json")).unwrap();
        let manifest: serde_json::Value = serde_json::from_str(&manifest_text).unwrap();
        assert_eq!(manifest["bundle_format_version"], 1);
        assert_eq!(
            manifest["source"]["commit"],
            crate::submodule::PINNED_COMMIT
        );
        assert_eq!(manifest["target_triple"], "x86_64-pc-windows-msvc");
        assert_eq!(manifest["toolkit_version"], "13.3");
        assert_eq!(manifest["architectures"], serde_json::json!(["120a-real"]));
        assert_eq!(manifest["linkage"], crate::manifest::LINKAGE_POLICY);
        assert_eq!(
            manifest["external_dlls"],
            serde_json::json!(["KERNEL32.dll", "cublas64_13.dll"])
        );
        assert_eq!(manifest["msvc"]["version"], "19.44.35219.0");
        let files = manifest["files"].as_array().unwrap();
        assert_eq!(files.len(), 2);
        assert_eq!(files[0]["name"], "ggml-cuda.dll");
        assert_eq!(files[0]["sha256"], sha256_hex(b"synthetic-dll"));
        assert_eq!(files[1]["name"], "llama-server.exe");
        assert_eq!(files[1]["sha256"], sha256_hex(b"synthetic-exe"));

        let codegen = std::fs::read_to_string(host.out_dir.join("llama_cuda_bundle.rs")).unwrap();
        assert!(codegen.contains("include_str!"));
        assert!(codegen.contains("(\"llama-server.exe\", include_bytes!"));
        assert!(codegen.contains("(\"ggml-cuda.dll\", include_bytes!"));

        let staged = host.out_dir.join("llama-cuda-bundle");
        assert_eq!(
            std::fs::read(staged.join("llama-server.exe")).unwrap(),
            b"synthetic-exe"
        );
        assert_eq!(
            std::fs::read(staged.join("ggml-cuda.dll")).unwrap(),
            b"synthetic-dll"
        );

        let invocations = probe.invocations();
        assert!(
            invocations
                .iter()
                .any(|line| line.contains("--list-devices"))
        );
        assert!(invocations.iter().any(|line| line.contains("/dependents")));
    }
}
